# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'firebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebase-tvOS

  target 'firebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
